cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    cl0803:
      email: cl0803@example.com
      name: cl0803
      password: $2b$12$.lE2xoqkNICqg4V8hv.kte0FzSw32KNGbnfAxqMtdc.gXpDeTmmIa
pre-authorized:
  emails:
  - melsby@gmail.com
