cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: admin@example.org
      name: admin
      password: $2b$12$nXVSJ0DvDqmmnQP8o2krV.6BGvBErrXINWxTBWTLFSpkKSEfvSzES
    x001:
      email: x001@example.org
      name: x001
      password: $2b$12$zQtekTahtxfZjGP4iUGc2OOFRQVEYWlUcOwj2IuTy10LXDDrMVx6C
pre-authorized:
  emails:
  - melsby@gmail.com
