# https://docs.streamlit.io/develop/api-reference/configuration/config.toml
# 
# streamlit config show

[client]
showErrorDetails = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[theme]
base="dark"
# primaryColor="#004a55"
# backgroundColor="#fafafa"
# textColor="#222"
font="sans serif"
